version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
            POSTGRES_HOST: localhost
            RAILS_ENV: test
      - image: cimg/postgres:14.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    working_directory: ~/jamtastic

    steps:
      - checkout

      - restore_cache:
          keys:
            - jamtastic-{{ .Branch }}{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --without development \
                           --deployment \
                           --jobs=3 \
                           --retry=3

      - save_cache:
          key: jamtastic-{{ .Branch }}{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      # Database setup
      - run: cp .env.example .env
      - run: bundle exec rake db:create

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run:
          name: run tests
          command: |
            bundle exec rspec
      - run: ./cc-test-reporter after-build --coverage-input-type simplecov
