default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  database: <%= ENV["POSTGRES_DEV_NAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  pool: <%= ENV["DATABASE_POOL"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["POSTGRES_TEST_NAME"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_PROD_NAME"] %>
