default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  database: <%= ENV["POSTGRES_DEV_NAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  pool: <%= ENV["DATABASE_POOL"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV["POSTGRES_PROD_NAME"] %>
